### ISSUE TITLE
Builder crashes if a saved module is removed from the blueprint

### ISSUE THREAD

**Issue by olach** [TimOetting/kirby-v3-builder#14]
Steps to reproduce:

1. Create some fieldsets for the Builder plugin.
```yml
label: Builder test
type: builder    

fieldsets:
  test1:
    label: Test1
    fields:
      text:
        label: Test1
        type: text
      
  test2:
    label: Test2
    fields:
      text:
        label: Test2
        type: text
```

2. On a page in the panel, add these two modules and save.

3. In the blueprint, remove the fieldset `test2`.

4. Refresh the page in the Panel. An error now shows: `Error in "modules" field Undefined index: test2`
