### ISSUE TITLE
Invalid return type of Kirby\Form\Field::save()

### ISSUE THREAD

**Issue by theWeird** [TimOetting/kirby-v3-builder#20]
- Occurred in latest composer installation (beta 6)
- Code cloned to site/plugins/kirby-v3-builder
- in site/plugins/kirby-v3-builder executed npm i && npm run build

After using the sandbox snippet in a plain default.yml blueprint (see below), I get this error message in the panel:
![image](https://user-images.githubusercontent.com/165980/50109384-e8944a00-0237-11e9-83da-03f4d44b0147.png)

blueprints/default.yml
```yaml
title: Default
#preset: page

fields:
  mybuilder:
    label: Page Builder
    type: builder
    columns: 1
    fieldsets:
      bodytext:
        label: Text Block (without preview but with tabs)
        tabs:
          content:
            label: Content
            icon: edit
            fields:
              text:
                label: text
                type: textarea
          style:
            label: Style
            icon: cog
            fields:
              fontfamily:
                label: Font
                type: select
                options:
                  helvetica: Helvetica
                  comicsans: Comic Sans
              fontsize:
                label: Font Size
                type: number
      quote:
        label: Quote
        preview:
          snippet: blocks/quote
          css: /assets/css/blocks/quote.css
        fields:
          text:
            label: Quote Text
            type: textarea
          citation:
            label: Citation
            type: text
      events:
        label: Events
        preview:
          snippet: blocks/events
          css: /assets/css/blocks/events.css
        fields:
          eventlist:
            type: builder
            label: Event List
            columns: 2
            fieldsets:
              event:
                label: Event
                fields:
                  title:
                    label: Title
                    type: text
                  text:
                    label: Description
                    type: textarea
                  date:
                    label: Date
                    type: date

```
