### ISSUE TITLE
No Tabs Structure in page.txt

### ISSUE THREAD

**Issue by tobiasfabian** [TimOetting/kirby-v3-builder#6]
Currently the structure of the tabs is saved into the page.txt

page.yml
``` yml
type: builder
fieldsets:
  test:
    tabs:
      tab-1:
        label: Tab 1
        fields:
          text-1:
            label: Text
            type: text
      tab-2:
        label: Tab 2
        fields:
          text-2:
            label: Text 2
            type: text
```

page.txt
```txt
- 
  _key: test
  tab-1:
    text-1: Lorem
  tab-2:
    text-2: Ipsum
```

I would prefer a flatter structure for the page.txt to separate Panel layout and content. This would allow the admin to remove, add or change tabs after content is already saved.

```txt
- 
  _key: test
  text-1: Lorem
  text-2: Ipsum
```
